### ISSUE TITLE
支持html文件外部样式表和js

### ISSUE THREAD

**Issue by arect** [valetzx/allblog#1]
原仓库`~/page/article/[id].vue`进行了[修改](https://github.com/arect/onedrive_blog/commit/b570830f463f542d6af4e734daa5b18f9f72a5bc)，使之可以支持html文件引用OneDrive的文件。但是仍有一定局限性。

_因为过于好奇第一个用户所以偷偷看了一下，如果打扰了不好意思。_

**Comment by valetzx** [comment]
好的真是太谢谢了，这blog除了挂api不就是让人看的嘛害没关系的(

**Comment by valetzx** [comment]
在更改`~/layouts/home.vue`时，`<div class="mx-2 cursor-pointer text-xl font-mono font-medium dark:text-green-100" @click="goHome">GoBack/Blog</div>`的内容如果有空格会自己换行？似乎，可以看一下虽然不是很影响（）

**Comment by arect** [comment]
> 在更改`~/layouts/home.vue`时，`<div class="mx-2 cursor-pointer text-xl font-mono font-medium dark:text-green-100" @click="goHome">GoBack/Blog</div>`的内容如果有空格会自己换行？似乎，可以看一下虽然不是很影响（）

你好，这里是当时对齐没有写好，我在自己仓库更新了，你可以去看一下。感谢捉虫。

**Comment by valetzx** [comment]
好的感谢！

**Comment by valetzx** [comment]
可以试试加个评论功能吗（感谢）[Valine](https://valine.js.org/)

**Comment by arect** [comment]
目前nuxt3对其它框架支持非常差，尝试了一下暂时加不了提到的评论系统。如果硬要做评论的话，可能要用到数据库或者OneDrive的写入权限，比较麻烦，所以暂时不打算加评论了。其实你也可以试一下[Hexo](https://hexo.io)。调用api的工作就交给网盘之类的。

**Comment by valetzx** [comment]
我写好了，但是似乎还是不调用文件中的 js `(已修改[id].vue)`

**Comment by valetzx** [comment]
我写好了，但是现在好像评论出不去([/Blog](https://onedrive-blog-valetzx.vercel.app/article/01VC3T5YY5RWDS4YEGS5FIKFG2G4DPLLXT)

**Comment by arect** [comment]
是我思维定势了，想把评论集成到博客里。
看了一下社区，大概是因为使用了LeanCloud国际版的问题，使用国内版即可正常使用（和博客没有关系）。
[本人测试](https://onedrive-blog.vercel.app/article/01DXDGLDEHQ6CJK2SHBNBJ43BJZLRCF5TF)

**Comment by valetzx** [comment]
好的感谢！

**Comment by valetzx** [comment]
今天又抄了好多内容（）可以来瞅瞅：[Pigpigeon's blog](https://onedrive-blog-valetzx.vercel.app/)
后面想要 置顶 文件夹套文件夹功能 音乐播放 （有点无礼）

**Comment by arect** [comment]
置顶可以手动排序`999-一篇文章`，文件夹嵌套，这样嵌下去就变成网盘了，音乐播放倒是可以，不过我想直接插入音频就足够了。

**Comment by valetzx** [comment]
想把东西分分类，涉及内容有点多（）或者能不能加搜索功能（）

**Comment by arect** [comment]
好的，我有时间试着去做一下。
主要自己前端比较差，界面不太好写😂

**Comment by valetzx** [comment]
好的麻烦了（音乐其实不急，可以调用qq音乐之类的接口？或者我那网盘再嵌一个进去也没啥）搜索还是比较方便的（尤其是能直接搜文章内容只类的~）感谢！

**Comment by arect** [comment]
搜索文章内容就做不到了，因为微软好像没有提供相关api，手动做就相当于要打开所有文件单独查找，需要大量时间。和浏览器打开所有文章然后搜索文字是差不多的。
这也是为什么会把序号放在文件夹标题上。
后续可以在标题上增加tag项目，比如`1-日常,教程-一篇文章`这样。然后做一个筛选。
但是……前端实在苦手。还是期待一下框架吧😢

（Hexo真的不错，也可以白嫖。

**Comment by valetzx** [comment]
害最近office开发者又出了个沙箱模式，可以新加1个域名(25个子账号)，我想一个网站能顺便挂两个调用内容就套了套。顺便还能更新github（github更新好像也能续订）盘里东西有点多，想这个号能（理论永久）

**Comment by valetzx** [comment]
想给整个博客加[百度流量检测](https://tongji.baidu.com/) 博客换了个域名重新部署了一下 [Blog](https://allblog.vercel.app/)

**Comment by valetzx** [comment]
是不是不能调用二级目录 img/xxx.png 之类的

**Comment by valetzx** [comment]
其实做文件夹还有个思路，不用做真文件夹，做成md这样大标题小标题这样的标签就可以 大标题一个文件夹，然后下面是小标题 # ## ### 这种，然后能做收起展开就更好了（）

**Comment by arect** [comment]
> 是不是不能调用二级目录 img/xxx.png 之类的

对，因为套一层就要访问一层api，再加上可能有各种情况，所以刻意没有做嵌套。

> 其实做文件夹还有个思路，不用做真文件夹，做成md这样大标题小标题这样的标签就可以 大标题一个文件夹，然后下面是小标题 # ## ### 这种，然后能做收起展开就更好了（）

markdown的解析我是交给`marked`来解析的，手动识别成本有点高。

**Comment by arect** [comment]
同时博客里的html解析，我是直接放进`iframe`标签内，所以你自己研究的时候可能需要考虑这一点。

**Comment by valetzx** [comment]
好的，我没怎么学过前端甚至html，很多都是百度了写的（

**Comment by valetzx** [comment]
页面格式可以支持php嘛（）

**Comment by valetzx** [comment]
有什么可以挂php的站点嘛 [已经抄好了](https://allblog.vercel.app/article/01VC3T5YYJAA6DG3CEFFALHJHOXITLQS6A) 用腾讯云搭的，调用od直链

**Comment by arect** [comment]
php是后端的啊……

**Comment by valetzx** [comment]
嗯，写了个随机图片调用作为我onedrive的背景，调用onedrive中的图片

**Comment by valetzx** [comment]
发现了一个很牛的特性，我[这个页面](https://allblog.vercel.app/article/01VC3T5YYJAA6DG3CEFFALHJHOXITLQS6A)中的文件夹如果有`index.html`之类的文件，blog也会帮你渲染，可以点进`!教程文档`看一下，里面的文件是`index.html`直接给渲染出来了，这样的话就不用在blog做文件夹分类了(可以去onedrive做，[onedrive本身的网址https://allonedrive.vercel.app/pig/](https://allonedrive.vercel.app/pig/)

**Comment by arect** [comment]
好奇你是怎么嵌套进去的……
我在昨天更新了仓库，添加了网页嵌套功能，但是因为`iframe`标签的局限性，一些网站会出现跨域问题，比如部分资源无法加载。还有网站比如百度，会阻止嵌套。

> 发现了一个很牛的特性，我[这个页面](https://allblog.vercel.app/article/01VC3T5YYJAA6DG3CEFFALHJHOXITLQS6A)中的文件夹如果有`index.html`之类的文件，blog也会帮你渲染……

确实是这样的，不过也算是iframe标签的行为，不是blog的功劳。

**Comment by valetzx** [comment]
确实，好像腾讯文档也会被拦截啥啥，我这里套的是别人的onedrive管理页吧，只要在onedrive传完整的内容，再把index直链，放进Blog文件夹中跳转就行了，应该是隔壁onedrive管理页权限多。蛮好的整个续订系统差不多了(
